<?php

namespace App\Enums;

/**
 * Operating mode of the mcmaco instance.
 *
 * - REAL: production store, no simulation. Real customers only.
 * - SIMULATION: demo / sandbox mode. Bot activity is generated by
 *   mcmaco:simulate:run, all simulated records carry is_simulated=true.
 * - DUAL: real customers + simulation running in parallel (future use).
 */
enum AppMode: string
{
    case REAL       = 'real';
    case SIMULATION = 'simulation';
    case DUAL       = 'dual';

    public function isSimulation(): bool
    {
        return $this === self::SIMULATION || $this === self::DUAL;
    }

    public function label(): string
    {
        return match ($this) {
            self::REAL       => 'Реальный магазин',
            self::SIMULATION => 'Симуляция',
            self::DUAL       => 'Смешанный режим',
        };
    }

    /**
     * Resolve the active mode from config. Defaults to REAL for safety —
     * a fresh install with no MCMACO_MODE set must never accidentally
     * start generating fake orders.
     */
    public static function active(): self
    {
        return self::tryFrom((string) config('simulation.mode', 'real')) ?? self::REAL;
    }
}
